alias cll='clear && ls -lG'
alias ll='ls -lG'
alias cc='clear'
alias la='ls -laG'
alias cla='clear && ls -laG'
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias cc='clear'
alias specr='vendor/bin/phpspec run --config=tests/spec/phpspec.yml.dist  --format=pretty --ansi --verbose'
alias spec='vendor/bin/phpspec'
alias behat='vendor/bin/behat'
alias j='jump'
